version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: cryptoforecastdatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: userpass123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-prootpass123"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql      # Initialize database with tables
    restart: unless-stopped

  api:
    build: .
    container_name: cryptoforecast-api
    environment:
      # Async DSN for the running app
      DATABASE_URL: mysql+aiomysql://myuser:userpass123@mysql:3306/cryptoforecastdatabase
      # DATABASE_URL: mysql+aiomysql://appuser:apppass123@mysql:3306/cryptoforecastdatabase?charset=utf8mb4
      SQL_ECHO: "0"
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 3s
      retries: 12
    volumes:
      # Hot reload during development (optional)
      - ./app:/app/app
    restart: unless-stopped

volumes:
  mysql_data: {}
