version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: cryptoforecasedatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: userpass123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-prootpass123"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql      # Initialize database with tables
    restart: unless-stopped

  api:
    build: .
    environment:
      # Async DSN for the running app
      DATABASE_URL: mysql+aiomysql://myuser:userpass123@mysql:3306/cryptoforecasedatabase
      SQL_ECHO: "0"
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    # Use wget OR curl; ensure your Dockerfile installs one of them
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/healthz"]
      # Alternative:
      # test: ["CMD-SHELL", "curl -fsS http://localhost:8080/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 12
    volumes:
      # Hot reload during development (optional)
      - ./app:/app/app
    restart: unless-stopped

volumes:
  mysql_data: {}
